#!/usr/bin/python
import time
import datetime
import Growl
import os
import sys
from Foundation import NSRunLoop, NSDate
from Foundation import NSArray, NSDistributedNotificationCenter, NSDictionary, NSNumber
from AppKit import NSWorkspace

class timeGrowlNotifier(Growl.GrowlNotifier):
    applicationName = 'Growl Time'
    notifications = ['Running Time - No Error','Running Time - Error']

n = timeGrowlNotifier(applicationIcon=NSWorkspace.sharedWorkspace().iconForFile_(
                                 NSWorkspace.sharedWorkspace().fullPathForApplication_("Terminal")))
n.register()
start = time.time()
exit = os.system(" ".join(sys.argv[1:]))
end = time.time()
start = datetime.datetime.fromtimestamp(start)
end = datetime.datetime.fromtimestamp(end)
if exit == 0:
    n.notify(n.notifications[0], 
             " ".join(sys.argv[1:]), 
             'Running Time=%s\nexit code=%s'%((end - start),exit)
             )
else:
    n.notify(n.notifications[1], 
             " ".join(sys.argv[1:]), 
             'Running Time=%s\nexit code=%s'%((end - start),exit),
             priority=Growl.growlPriority["High"]
             )

sys.exit(exit)
