//
//  $Id$
//
//  Copyright 2007 The Growl Project. All rights reserved.
//
// This file is under the BSD License, refer to license.txt for details

#include "nsISupports.idl"
#include "nsIObserver.idl"

[scriptable, uuid(a8367114-c32d-43e2-9ba5-70e5e64f3719)]
interface grINotifications : nsISupports
{
  /**
   * Dispatches a notification to Growl.
   *
   * @param aName The name of the notification.
   * @param aImage The url of the image to use.
   * @param aTitle The title to display for the notification.
   * @param aMessage The message body of the notification.
   * @param aData The data to pass along back to the observer.
   * @param aObserver The observer that will look for clickbacks
   */
  void sendNotification(in AString aName, in AString aImage, in AString aTitle,
                        in AString aMessage, in AString aData,
                        in nsIObserver aObserver);

  /**
   * Grabs focus for the application from the operating system
   */
   void makeAppFocused();
};

[scriptable, uuid(11e0176a-4a2d-4a90-8dcc-1590eeb1769d)]
interface grINotificationsList : nsISupports
{
  /**
   * Adds a notification to the registration dictionary.
   *
   * @param aName The name of the notification we might be sending.
   * @param aEnabled Indicates if the notification is enabled by default.
   */
  void addNotification(in AString aName, in boolean aEnabled);

  /**
   * Checks to see if a paticular notification has already been registered.
   *
   * @param aName The name of the notification we are checking against.
   */
  boolean isNotification(in AString aName);
};
