#!/bin/sh
defaults write /Library/Preferences/com.apple.mail EnableBundles 1
defaults write /Library/Preferences/com.apple.mail BundleCompatibilityVersion 2

OLD_LOCATION=$HOME/Library/Mail/Bundles/GrowlMail.mailbundle
TRASH=$HOME/.Trash
if [ -d $OLD_LOCATION ]; then
	echo Moving old installation in $OLD_LOCATION to $TRASH
	mv $OLD_LOCATION $TRASH
fi
