//
//  GrowlMailMeDisplay.m
//  Growl Display Plugins
//
//  Copyright 2004 Mac-arena the Bored Zo. All rights reserved.
//
#import "GrowlMailMeDisplay.h"
#import "GrowlMailMePrefs.h"

static NSString *author      = @"Mac-arena the Bored Zo";
static NSString *name        = @"MailMe";
static NSString *description = @"MailMe like notifications, with a twist";
static NSString *version     = @"1.0a1";

static NSString *destAddressKey = @"MailMe - Recipient address";

static NSString *plainTextMessageFormat = /*for when there is no icon*/
	@"%@\r\n"
	@"-- This message was automatically generated by MailMe, a Growl plug-in, --\r\n"
	@"-- in response to a Growl notification --\r\n"
	@"-- http://growl.info/ --\r\n";

@class NSPreferencePane;

@implementation GrowlMailMeDisplay

- (id)init {
	if( (self = [super init] ) ) {
		prefPane = [[GrowlMailMePrefs alloc] initWithBundle:[NSBundle bundleForClass:[GrowlMailMePrefs class]]];
	}
	return self;
}

- (void)dealloc {
	[prefPane release];
	[super dealloc];
}

- (void)loadPlugin {
}

- (NSString *)author {
	return author;
}

- (NSString *)name {
	return name;
}

- (NSString *)userDescription {
	return description;
}

- (NSString *)version {
	return version;
}

- (void)unloadPlugin {
}

- (NSDictionary *)pluginInfo {
	return [NSDictionary dictionaryWithObjectsAndKeys:
		name,        @"Name",
		author,      @"Author",
		version,     @"Version",
		description, @"Description",
		nil];
}

- (NSPreferencePane *)preferencePane {
	return prefPane;
}

- (void)displayNotificationWithInfo:(NSDictionary *)noteDict {
	READ_GROWL_PREF_VALUE(destAddressKey, @"com.Growl.MailMe", NSString *, &destAddress);

	NSString *title = [noteDict objectForKey:GROWL_NOTIFICATION_TITLE];
	NSString *desc = [noteDict objectForKey:GROWL_NOTIFICATION_DESCRIPTION];
	//hopefully something can be worked out to use the imageData.
	//documentation, Apple, documentation!
//	NSData *imageData = [noteDict objectForKey:GROWL_NOTIFICATION_ICON];

	BOOL success = [NSMailDelivery deliverMessage:[NSString stringWithFormat:plainTextMessageFormat, desc]
										  subject:title
											   to:destAddress];

	if(!success) {
		NSLog(@"(MailMe) WARNING: Could not send email message \"%@\" to address %@", title, destAddress);
		NSLog(@"(MailMe) description of notification:\n%@", desc);
	} else
		NSLog(@"(MailMe) Successfully sent message \"%@\" to address %@", title, destAddress);

	destAddress = nil;
}

@end
