//
//  GrowlMailMeDisplay.m
//  Growl Display Plugins
//
//  Copyright 2004 Mac-arena the Bored Zo. All rights reserved.
//
#import "GrowlMailMeDisplay.h"
#import "GrowlMailMePrefs.h"
#import <Message/NSMailDelivery.h>
#import <GrowlDefinesInternal.h>
#import <GrowlDisplayProtocol.h>

#define AUTHOR		@"Mac-arena the Bored Zo"
#define NAME		@"MailMe"
#define DESCRIPTION	@"MailMe like notifications, with a twist"
#define VERSION		@"1.0a1"

#define destAddressKey @"MailMe - Recipient address"

/* for when there is no icon */
#define plainTextMessageFormat @"%@\r\n"\
	@"-- This message was automatically generated by MailMe, a Growl plug-in, --\r\n"\
	@"-- in response to a Growl notification --\r\n"\
	@"-- http://growl.info/ --\r\n"

@implementation GrowlMailMeDisplay

- (id) init {
	if ( (self = [super init] ) ) {
		prefPane = [[GrowlMailMePrefs alloc] initWithBundle:[NSBundle bundleForClass:[GrowlMailMePrefs class]]];
	}
	return self;
}

- (void) dealloc {
	[prefPane release];
	[super dealloc];
}

- (void) loadPlugin {
}

- (NSString *) author {
	return AUTHOR;
}

- (NSString *) name {
	return NAME;
}

- (NSString *) userDescription {
	return DESCRIPTION;
}

- (NSString *) version {
	return VERSION;
}

- (void) unloadPlugin {
}

- (NSDictionary *) pluginInfo {
	return [NSDictionary dictionaryWithObjectsAndKeys:
		NAME,			@"Name",
		AUTHOR,			@"Author",
		VERSION,		@"Version",
		DESCRIPTION,	@"Description",
		nil];
}

- (NSPreferencePane *) preferencePane {
	return prefPane;
}

- (void) displayNotificationWithInfo:(NSDictionary *)noteDict {
	READ_GROWL_PREF_VALUE(destAddressKey, @"com.Growl.MailMe", NSString *, &destAddress);

	NSString *title = [noteDict objectForKey:GROWL_NOTIFICATION_TITLE];
	NSString *desc = [noteDict objectForKey:GROWL_NOTIFICATION_DESCRIPTION];
	//hopefully something can be worked out to use the imageData.
	//documentation, Apple, documentation!
//	NSData *imageData = [noteDict objectForKey:GROWL_NOTIFICATION_ICON];

	BOOL success = [NSMailDelivery deliverMessage:[NSString stringWithFormat:plainTextMessageFormat, desc]
										  subject:title
											   to:destAddress];

	if (!success) {
		NSLog(@"(MailMe) WARNING: Could not send email message \"%@\" to address %@", title, destAddress);
		NSLog(@"(MailMe) description of notification:\n%@", desc);
	} else
		NSLog(@"(MailMe) Successfully sent message \"%@\" to address %@", title, destAddress);

	destAddress = nil;
}

@end
