#!/bin/sh
###############
#
# Usage: update_growl_from_bundle SOURCE_BUNDLE_PATH LANGUAGE_NAME
#        for example:
#            ~/bin/update_growl_from_bundle Desktop/Growl_French.prefPane French
#
# Set REPO to your Growl repository
#
# To add a new language, the language should first be added in XCode and added to
# the repository with svn add. Then, run the script to copy in the localizations.
#
# This script does not cover Growl-WithInstaller.framework or Growl Extras.
################
REPO=~/growl

SOURCE=$1
LANG=$2.lproj

cd "$SOURCE/Contents/Resources"

########
# Functions
########

# Copy all nibs and other files in the current directory to a given destination
loc_copy()
{
    find . '(' -name "*.nib" ')' -prune -execdir cp "{}/classes.nib" "$1/{}" ';'
    find . '(' -name "*.nib" ')' -prune -execdir cp "{}/keyedobjects.nib" "$1/{}" ';'
    cp * $1
}


# Main resources (PrefPane)
pushd $LANG
loc_copy "$REPO/Core/Resources/$LANG"
popd

# Growl Helper App (which includes all the display plugins)
pushd GrowlHelperApp.app/Contents
pushd Resources/$LANG
    #GHA's localizable.strings goes to the same place as the prefpanne's
    cp Localizable.strings "$REPO/Core/Resources/$LANG"
popd

    # Plugins
    pushd PlugIns
    for plugin in *.growlView do
        pushd $plugin/Contents/Resources/$LANG
            PLUGIN_NAME=`echo $plugin | cut -f1 -d .`
            loc_copy "$REPO/Plugins/Displays/$PLUGIN_NAME/$LANG"
        popd
    fi
    popd

# GrowlMenu
pushd GrowlMenu.app/Contents/Resources/$LANG
    loc_copy "$REPO/StatusItem/Resources/$LANG"
popd


